### ISSUE TITLE
Error when start the server

### ISSUE THREAD

**Issue by zhliao** [IBM/evote#22]
Hi, 
  I am following the run-local steps and everything was well. But I got an error when I tried to start the server in Step 6. Here is the output:

$ npm start

> server@1.0.0 start /home/ubuntu1804/BlockChainProjects/evote/web-app/server
> ./node_modules/nodemon/bin/nodemon.js src/app.js

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/app.js`
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/ubuntu1804/BlockChainProjects/evote/web-app/server/ibpConnection.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/ubuntu1804/BlockChainProjects/evote/web-app/server/src/fabric/network.js:20:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[nodemon] app crashed - waiting for file changes before starting...

My vscode version is 1..39.2 
My IBP extension is 1.0.23

Could you please help me figure out the problem? 

Thanks

**Comment by zhliao** [comment]
I re-export the fabric_connection.json file and redo the step 5. It works. Thank you!
